### ISSUE TITLE
Add artworks count to AreaListItems

### ISSUE THREAD

**Issue by rnackman** [mplusmuseum/mplusmuseum-www#110]

**Comment by erchaves** [comment]
@micahwalter I believe this is done now. Though, we don't really have the data to test correctly. But this page shows "0 artworks" for everything https://collections.mplus.org.hk/areas

The logic accounts for plural strings:
```
const getArtworkCountString  = (artworksLength) => {
  const pluralS = parseInt(artworksLength, 10) !== 1 ? 's' : ''

  return `${artworksLength} artwork${pluralS}`
}
```
