### ISSUE TITLE
Show images in spelunker

### ISSUE THREAD

**Issue by jedahan** [mplusmuseum/mplusmuseum-www#112]

**Comment by revdancatt** [comment]
It's the job of the extractor to copy the images uploaded to the tms-extractor server to S3 and generate various image sizes. The spelunker should then point to those images (if they exist).

**Comment by erchaves** [comment]
This is done now -- you can see an example here: https://collections.mplus.org.hk/collection/objects/1814

The same image is not showing up on staging, but I think it's just because staging needs the TMS extract run.
