### ISSUE TITLE
Expose www via ELB

### ISSUE THREAD

**Issue by micahwalter** [mplusmuseum/mplusmuseum-www#113]
We can point an AWS ELB at this. We should also have a separate one for the GraphQL endpoint.

**Comment by micahwalter** [comment]
I've set up the ELB for the staging server. It's here

http://staging.mplus.org.hk/

We need to 

- [ ] Add support for https

- [ ] Set up another one for GraphQL endpoint

- [ ] Do this all over again for production.

**Comment by jedahan** [comment]
- [ ] hide http://admin.mplus.org.hk:3001/

**Comment by micahwalter** [comment]
These are set up, just waiting on DNS entries and new EC2 instances.
