### ISSUE TITLE
Create ansible or bash scripts to setup default environment.

### ISSUE THREAD

**Issue by revdancatt** [mplusmuseum/mplusmuseum-www#115]
To make spinning up and deploying servers super easy we should probably set something up with ansible or bash so make everything as easy as possible for a user.

**Comment by erchaves** [comment]
Oh, I just saw this ticket. I made this bash script. It's still a bit of a work in progress.
https://docs.google.com/document/d/1qqUBgdcl5CReiglpZua7h0hp2EZsnv3IUAABunWOSPc/edit

**Comment by micahwalter** [comment]
Lets continue what we did for TMS Extract and GrpahQL here when its time.
