### ISSUE TITLE
Images in API

### ISSUE THREAD

**Issue by dianewang** [mplusmuseum/mplusmuseum-www#141]
Hi @micahwalter, looking through the spelunker, I'm finding that a number of objects from the Sigg Online don't have images but should. Some links below:

Not sure where the TMS folder these images are pulling from are from?

https://collections.mplus.org.hk/collections/objects/2207
https://collections.mplus.org.hk/collections/objects/2091
https://collections.mplus.org.hk/collections/objects/3011
https://collections.mplus.org.hk/collections/objects/2802

On the other hand, some do:
https://collections.mplus.org.hk/collections/objects/2223

**Comment by micahwalter** [comment]
[dan@micahwalter.com](https://app.asana.com/0/567213203428857/567213203428857) can we do a little data verification here - what’s in the folder we are processing vs. what’s in the XML.. ?

**Comment by revdancatt** [comment]
Sure, I know for a fact that some of the images location references provided by TMS don't match up with images exported on the file system. This is actually known and held in a record by the dashboard/extractor, I just need to list it on the dashboard to people can see what's missing (and fix it).

**Comment by revdancatt** [comment]
Closing this as it's now replicated over at: https://github.com/mplusmuseum/mplusmuseum-tms-extract/issues/81
