### ISSUE TITLE
Going 'back' to a Search

### ISSUE THREAD

**Issue by dianewang** [mplusmuseum/mplusmuseum-www#142]
Noticing that when I search something and then click on an individual object, there's no way for me to go 'back' to a search. If I click the back button, it'll reset to all the objects. This might be something we want to build in?

**Comment by micahwalter** [comment]
[eric@micahwalter.com](https://app.asana.com/0/567213203428870/567213203428870) let’s fix this basic UI thing - can we put a search box in the main nav that is global to all pages - searches across all fields and first class objects etc?

**Comment by micahwalter** [comment]
Instead of "filtering" can we just show a search results page? with pretty query urls and all that?
