### ISSUE TITLE
Logged-out home page

### ISSUE THREAD

**Issue by rnackman** [mplusmuseum/mplusmuseum-www#84]

**Comment by rnackman** [comment]
Should this include a collection of bookmarks?

**Comment by revdancatt** [comment]
Dependent on #96

**Comment by revdancatt** [comment]
We need documentation of what appears on the Logged out homepage, unless that already exists?

**Comment by erchaves** [comment]
Closing this for now - we can recreate from a proper spec later after we get UX.
