### ISSUE TITLE
Upload images to somewhere

### ISSUE THREAD

**Issue by jedahan** [mplusmuseum/mplusmuseum-www#92]
local or s3

**Comment by jedahan** [comment]
Uploading to `mplus-admin:/usr/local/mplusmuseum/media-thumbnails/{1024, 480}`

**Comment by revdancatt** [comment]
This should probably be closed and moved to the mplusmuseum/mplusmuseum-tms-extract project as that deals with the ingestion of the .xml and images?

**Comment by jedahan** [comment]
yeah, this should be automated in there

**Comment by revdancatt** [comment]
Cheers, closing this and adding images as a task to mplusmuseum-tms-extract instead.
