### ISSUE TITLE
bookmarks

### ISSUE THREAD

**Issue by jedahan** [mplusmuseum/mplusmuseum-www#94]
first without auth - just being able to share links

**Comment by revdancatt** [comment]
Is this just having bookmarkable URLs that when revisited show the same item... like how webpages normally work? Or is there more to it than that?

**Comment by jedahan** [comment]
I think the idea was that you could favorite a bunch of objects on the website, and then share those as a collection. So like, an on-site bookmarker and viewer of said objects. Think 'pinning' results of a search and then being able to bring those up.
