### ISSUE TITLE
Setup frontend authentication

### ISSUE THREAD

**Issue by jedahan** [mplusmuseum/mplusmuseum-www#97]
using passport

**Comment by micahwalter** [comment]
@jedahan @revdancatt @erchaves - Not sure who is available, but let's please put the site behind a basic username/password auth asap. Same for the GraphQL API.

**Comment by erchaves** [comment]
@revdancatt as we discussed I'll handle the part of this on the node server. I'll check in with you after that to see if I can help with any other part of it as well

**Comment by micahwalter** [comment]
basic htpass auth is in place
